name: redmi6a_kernel
on:
  workflow_dispatch:
jobs:
  build:
    name: "Build kernel"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Kernel
      run: |
        chmod a+x ./build.sh
        ./build.sh
      shell: bash
